Cast is*/to* arguments to proper type.
Fixes
error: array subscript has type ‘char’ [-Werror=char-subscripts]
on NetBSD, which is picky about its ctype(3) function arguments.